language: c
sudo: required
dist: trusty
services:
  - docker
python:
  - "2.7"
compiler:
- gcc
os:
- linux
env:
  global:

before_install:
- echo $LANG
- echo $LC_ALL
- test -n $CC && unset CC
before_script:
- echo "install packages"
install:
- sudo apt-get update
- sudo apt-get install gfortran gfortran-multilib libquadmath0
script:
- cd src && make all
  # - if [ $TRAVIS_OS_NAME == linux ]; then sudo ./build-script.sh; fi
after_success:
- echo "TODO make flopy modflow test"
  # - echo "TODO make docker"
branches:
  only:
  - master
  - "/^v\\d+\\./"

notifications:
  email:
  - allixender@googlemail.com
